# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: samples.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='samples.proto',
  package='DRL',
  syntax='proto2',
  serialized_options=b'\200\001\001',
  serialized_pb=b'\n\rsamples.proto\x12\x03\x44RL\"k\n\x06Sample\x12\x11\n\x05state\x18\x01 \x03(\x02\x42\x02\x10\x01\x12\x12\n\x06\x61\x63tion\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\x11\n\x06reward\x18\x03 \x02(\x02:\x01\x30\x12\x16\n\nnext_state\x18\x04 \x03(\x02\x42\x02\x10\x01\x12\x0f\n\x04mask\x18\x05 \x01(\x02:\x01\x31\":\n\x07\x45pisode\x12\x1c\n\x07samples\x18\x01 \x03(\x0b\x32\x0b.DRL.Sample\x12\x11\n\tworker_id\x18\x02 \x01(\x05\"#\n\x0c\x45mptyRequest\x12\x13\n\x0bplaceholder\x18\x01 \x01(\x05\"!\n\x0bReadRequest\x12\x12\n\nbatch_size\x18\x01 \x01(\x05\"4\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12\x12\n\nerror_text\x18\x02 \x01(\t\"0\n\x0fShmInfoResponse\x12\r\n\x05shmid\x18\x01 \x02(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"N\n\x10StatInfoResponse\x12\x13\n\x0bnum_samples\x18\x01 \x02(\x03\x12\x11\n\tnum_reads\x18\x02 \x02(\x05\x12\x12\n\nnum_writes\x18\x03 \x02(\x05\x32\x96\x03\n\x0eMempoolService\x12\x34\n\nHelloWorld\x12\x11.DRL.EmptyRequest\x1a\x13.DRL.StatusResponse\x12\x30\n\x0bSaveSamples\x12\x0c.DRL.Episode\x1a\x13.DRL.StatusResponse\x12\x34\n\x0bReadSamples\x12\x10.DRL.ReadRequest\x1a\x13.DRL.StatusResponse\x12\x38\n\x0e\x43loseShmBuffer\x12\x11.DRL.EmptyRequest\x1a\x13.DRL.StatusResponse\x12\x37\n\x0bGetStatInfo\x12\x11.DRL.EmptyRequest\x1a\x15.DRL.StatInfoResponse\x12\x35\n\nGetShmInfo\x12\x11.DRL.EmptyRequest\x1a\x14.DRL.ShmInfoResponse\x12<\n\x12\x44ownloadModelFiles\x12\x11.DRL.EmptyRequest\x1a\x13.DRL.StatusResponseB\x03\x80\x01\x01'
)




_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='DRL.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='DRL.Sample.state', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='DRL.Sample.action', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward', full_name='DRL.Sample.reward', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_state', full_name='DRL.Sample.next_state', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mask', full_name='DRL.Sample.mask', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=129,
)


_EPISODE = _descriptor.Descriptor(
  name='Episode',
  full_name='DRL.Episode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='samples', full_name='DRL.Episode.samples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='DRL.Episode.worker_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=189,
)


_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='DRL.EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='placeholder', full_name='DRL.EmptyRequest.placeholder', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=226,
)


_READREQUEST = _descriptor.Descriptor(
  name='ReadRequest',
  full_name='DRL.ReadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='DRL.ReadRequest.batch_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=261,
)


_STATUSRESPONSE = _descriptor.Descriptor(
  name='StatusResponse',
  full_name='DRL.StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='DRL.StatusResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_text', full_name='DRL.StatusResponse.error_text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=315,
)


_SHMINFORESPONSE = _descriptor.Descriptor(
  name='ShmInfoResponse',
  full_name='DRL.ShmInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shmid', full_name='DRL.ShmInfoResponse.shmid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='DRL.ShmInfoResponse.offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=365,
)


_STATINFORESPONSE = _descriptor.Descriptor(
  name='StatInfoResponse',
  full_name='DRL.StatInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_samples', full_name='DRL.StatInfoResponse.num_samples', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_reads', full_name='DRL.StatInfoResponse.num_reads', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_writes', full_name='DRL.StatInfoResponse.num_writes', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=445,
)

_EPISODE.fields_by_name['samples'].message_type = _SAMPLE
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
DESCRIPTOR.message_types_by_name['Episode'] = _EPISODE
DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['ReadRequest'] = _READREQUEST
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE
DESCRIPTOR.message_types_by_name['ShmInfoResponse'] = _SHMINFORESPONSE
DESCRIPTOR.message_types_by_name['StatInfoResponse'] = _STATINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLE,
  '__module__' : 'samples_pb2'
  # @@protoc_insertion_point(class_scope:DRL.Sample)
  })
_sym_db.RegisterMessage(Sample)

Episode = _reflection.GeneratedProtocolMessageType('Episode', (_message.Message,), {
  'DESCRIPTOR' : _EPISODE,
  '__module__' : 'samples_pb2'
  # @@protoc_insertion_point(class_scope:DRL.Episode)
  })
_sym_db.RegisterMessage(Episode)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYREQUEST,
  '__module__' : 'samples_pb2'
  # @@protoc_insertion_point(class_scope:DRL.EmptyRequest)
  })
_sym_db.RegisterMessage(EmptyRequest)

ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), {
  'DESCRIPTOR' : _READREQUEST,
  '__module__' : 'samples_pb2'
  # @@protoc_insertion_point(class_scope:DRL.ReadRequest)
  })
_sym_db.RegisterMessage(ReadRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'samples_pb2'
  # @@protoc_insertion_point(class_scope:DRL.StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)

ShmInfoResponse = _reflection.GeneratedProtocolMessageType('ShmInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHMINFORESPONSE,
  '__module__' : 'samples_pb2'
  # @@protoc_insertion_point(class_scope:DRL.ShmInfoResponse)
  })
_sym_db.RegisterMessage(ShmInfoResponse)

StatInfoResponse = _reflection.GeneratedProtocolMessageType('StatInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATINFORESPONSE,
  '__module__' : 'samples_pb2'
  # @@protoc_insertion_point(class_scope:DRL.StatInfoResponse)
  })
_sym_db.RegisterMessage(StatInfoResponse)


DESCRIPTOR._options = None
_SAMPLE.fields_by_name['state']._options = None
_SAMPLE.fields_by_name['action']._options = None
_SAMPLE.fields_by_name['next_state']._options = None

_MEMPOOLSERVICE = _descriptor.ServiceDescriptor(
  name='MempoolService',
  full_name='DRL.MempoolService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=448,
  serialized_end=854,
  methods=[
  _descriptor.MethodDescriptor(
    name='HelloWorld',
    full_name='DRL.MempoolService.HelloWorld',
    index=0,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SaveSamples',
    full_name='DRL.MempoolService.SaveSamples',
    index=1,
    containing_service=None,
    input_type=_EPISODE,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReadSamples',
    full_name='DRL.MempoolService.ReadSamples',
    index=2,
    containing_service=None,
    input_type=_READREQUEST,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CloseShmBuffer',
    full_name='DRL.MempoolService.CloseShmBuffer',
    index=3,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStatInfo',
    full_name='DRL.MempoolService.GetStatInfo',
    index=4,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_STATINFORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetShmInfo',
    full_name='DRL.MempoolService.GetShmInfo',
    index=5,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_SHMINFORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DownloadModelFiles',
    full_name='DRL.MempoolService.DownloadModelFiles',
    index=6,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_STATUSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEMPOOLSERVICE)

DESCRIPTOR.services_by_name['MempoolService'] = _MEMPOOLSERVICE

# @@protoc_insertion_point(module_scope)
